### ISSUE TITLE
urllib2.HTTPError: HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by EasyAsABC123** [paultravers/destiny_calcified_fragments#2]
New issue using latest, also you have to use %20 if you have a space in GT

```
$ ./dest_cf.py XBL "ll%20abc123%20ll"
Traceback (most recent call last):
  File "./dest_cf.py", line 33, in <module>
    response3 = urllib2.urlopen(req3)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by EasyAsABC123** [comment]
this is the code I wrote that is working 100%...

``` python
#! /usr/bin/env python
import urllib2, json, sys

if len(sys.argv) != 3:
    print """Usage: %s (XBL|PSN) (Username)

NOTE: You may have to enclose your username in quotes if it 
contains spaces or other non-alphanumeric characters"""
    sys.exit(1)

if sys.argv[1] == 'XBL':
    system = 1
else:
    system = 2

apikey = "YOUR_API_KEY_HERE"
playerName = sys.argv[2]

url3 = "http://www.bungie.net/Platform/Destiny/SearchDestinyPlayer/%s/%s/" % (system, playerName)

req = urllib2.Request(url3, None, {'X-API-Key' : apikey})
req.add_header('X-API-Key', apikey)
resp = urllib2.urlopen(req)

data3 = json.loads(resp.read())

playerId = data3['Response'][0]['membershipId']

url = "http://www.bungie.net/Platform/Destiny/Vanguard/Grimoire/%s/%s/" % (system, playerId)

url2 = "http://www.bungie.net/Platform/Destiny/Vanguard/Grimoire/Definition/"

req = urllib2.Request(url2, None, {'X-API-Key' : apikey})
req.add_header('X-API-Key', apikey)
response = urllib2.urlopen(req)

req = urllib2.Request(url, None, {'X-API-Key' : apikey})
req.add_header('X-API-Key', apikey)
response2 = urllib2.urlopen(req)

data = json.loads(response2.read())

grimoire_data = json.loads(response.read())

cards = data['Response']['data']['cardCollection']

frags = [ 700750 , 700680 , 700690 , 700700 , 700710 , 700720 , 700730 , 700740 , 700760 , 700770 , 700780 , 700790 , 700800 , 700810 , 700820 , 700830 , 700840 , 700850 , 700860 , 700870 , 700880 , 700890 , 700900 , 700910 , 700920 , 700930 , 700940 , 700950 , 700960 , 700970 , 700980 , 700990 , 701000 , 701010 , 701020 , 701030 , 701040 , 701050 , 701060 , 701070 , 701080 , 701090 , 701100 , 701110 , 701120 , 701130 , 701140 , 701150 , 701160 , 701170 ]

frags_org = frags[:]

carddb = {}

for card in cards:
    if card['cardId'] in frags:
        frags.remove(card['cardId'])


for theme in grimoire_data['Response']['themeCollection']:
    for page in theme['pageCollection']:
        for card in page['cardCollection']:
            cardId = card['cardId']
            cardName = card['cardName'].encode('utf-8', 'ignore')
            cardDescription = card['cardDescription'].encode('utf-8', 'ignore')
            if cardId in frags_org:
                frag_num = frags_org.index(cardId) + 1
            else:
                frag_num = -1

            carddb[cardId] = [cardName, cardDescription, frag_num]


for frag in frags:
    print '-------'
    print carddb[frag][0]
    print '-------'

print 'Total Fragments Found: ' + str(len(frags_org) - len(frags))

```

**Comment by paultravers** [comment]
Feel free to submit as a PR and I'll give it a quick glance over. Also thanks for checking over this!

**Comment by EasyAsABC123** [comment]
This code isn't cleaned or what i'd consider PR ready, just giving a point of reference.

As I state in #3, there isn't a benefit to using this over ghosthunter...if it was character based there would be

**Comment by paultravers** [comment]
Updated code with support for usernames with spaces and better handling of users not entering XBL or PSN flags
